// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class ConstructionSite
{
    public int id { get; set; }

    public int project_id { get; set; }

    public int employeeResponsible_id { get; set; }

    public string name { get; set; }

    public string adress { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public int? zipCode { get; set; }

    public DateTime startDate { get; set; }

    public DateTime? endDate { get; set; }

    public DateTime dueDate { get; set; }

    public virtual ICollection<CSiteIssue> CSiteIssues { get; set; } = new List<CSiteIssue>();

    public virtual ICollection<CSiteTask> CSiteTasks { get; set; } = new List<CSiteTask>();

    public virtual ICollection<ToolAssignmentCsite> ToolAssignmentCsites { get; set; } = new List<ToolAssignmentCsite>();

    public virtual ICollection<VehicleAssignmentCSite> VehicleAssignmentCSites { get; set; } = new List<VehicleAssignmentCSite>();

    public virtual Employee employeeResponsible { get; set; }

    public virtual Project project { get; set; }
}