// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class CSiteTaskStep
{
    public int id { get; set; }

    public int cSiteTask_id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string status { get; set; }

    public virtual CSiteTask cSiteTask { get; set; }
}