// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class CSiteTask
{
    public int id { get; set; }

    public int constructionSite_id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? locationOnSite { get; set; }

    public DateTime dateOfSubmission { get; set; }

    public DateTime? dateOfClosing { get; set; }

    public DateTime dueDate { get; set; }

    public string status { get; set; }

    public string priority { get; set; }

    public virtual ICollection<CSiteImage> CSiteImages { get; set; } = new List<CSiteImage>();

    public virtual ICollection<CSiteTaskStep> CSiteTaskSteps { get; set; } = new List<CSiteTaskStep>();

    public virtual ConstructionSite constructionSite { get; set; }
}