// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class EmployeeAssignmentCSite
{
    public int ConstructionSiteid { get; set; }

    public int Employeeid { get; set; }

    public DateTime assignmentStartDate { get; set; }

    public DateTime? assignmentEndDate { get; set; }

    public virtual ConstructionSite ConstructionSite { get; set; }

    public virtual Employee Employee { get; set; }
}