// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Employee
{
    public int id { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public long? oib { get; set; }

    public string phone { get; set; }

    public string adress { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public long? zipCode { get; set; }

    public string bankAccountNumber { get; set; }

    public string notes { get; set; }

    public int? hourlyPay { get; set; }

    public int statusOfEmployment { get; set; }

    public int isOnLeave { get; set; }

    public virtual ICollection<ConstructionSite> ConstructionSites { get; set; } = new List<ConstructionSite>();

    public virtual ICollection<EmployeeAssignmentCSite> EmployeeAssignmentCSites { get; set; } = new List<EmployeeAssignmentCSite>();

    public virtual ICollection<ToolAssignmentCsite> ToolAssignmentCsites { get; set; } = new List<ToolAssignmentCsite>();

    public virtual ICollection<VehicleAssignmentCSite> VehicleAssignmentCSites { get; set; } = new List<VehicleAssignmentCSite>();
}