// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class FacadeProject
{
    public int facade_project_id { get; set; }

    public int project_id { get; set; }

    public int glassProject_id { get; set; }

    public int profileSupplier_id { get; set; }

    public string status { get; set; }

    public string name { get; set; }

    public string profile { get; set; }

    public virtual GlassForProject glassProject { get; set; }

    public virtual ProfileSupplier profileSupplier { get; set; }

    public virtual Project project { get; set; }
}