// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class File
{
    public int id { get; set; }

    public int project_id { get; set; }

    public int projectType { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public byte[] fileData { get; set; }

    public string fileType { get; set; }

    public string filePath { get; set; }

    public string fileSize { get; set; }

    public DateTime? uploadDate { get; set; }

    public virtual Project project { get; set; }
}