// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class GlassForSubproject
{
    public int glassProject_id { get; set; }

    public string status { get; set; }

    public string name { get; set; }

    public int? subproject_id { get; set; }

    public virtual ICollection<GlazedGlass> GlazedGlasses { get; set; } = new List<GlazedGlass>();

    public virtual Subproject subproject { get; set; }
}