// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class GlassType
{
    public int id { get; set; }

    public string shortName { get; set; }

    public string name { get; set; }

    public string glassThicknesses { get; set; }
}