// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class GlassConfiguration
{
    public int id { get; set; }

    public string shortName { get; set; }

    public string name { get; set; }

    public double? thickness { get; set; }

    public int? noOfGlassPieces { get; set; }

    public string configuration { get; set; }

    public int argon { get; set; }

    public virtual ICollection<GlazedGlass> GlazedGlasses { get; set; } = new List<GlazedGlass>();
}