// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class GlassPiece
{
    public int GlazedGlassid { get; set; }

    public int? glassThickness { get; set; }

    public int? width { get; set; }

    public int? height { get; set; }

    public int id { get; set; }

    public virtual GlazedGlass GlazedGlass { get; set; }
}