// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class GlassForProject
{
    public int glassProject_id { get; set; }

    public string status { get; set; }

    public string name { get; set; }

    public virtual ICollection<ALUProject> ALUProjects { get; set; } = new List<ALUProject>();

    public virtual ICollection<DoorProject> DoorProjects { get; set; } = new List<DoorProject>();

    public virtual ICollection<FacadeProject> FacadeProjects { get; set; } = new List<FacadeProject>();

    public virtual ICollection<GlazedGlass> GlazedGlasses { get; set; } = new List<GlazedGlass>();

    public virtual ICollection<PVCProject> PVCProjects { get; set; } = new List<PVCProject>();
}