// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class GlazedGlass
{
    public int id { get; set; }

    public int glassConfiguration_id { get; set; }

    public int glassProject_id { get; set; }

    public string position { get; set; }

    public int? hasOrnamentSpacer { get; set; }

    public int? hasOrnamentGlass { get; set; }

    public virtual ICollection<GlassPiece> GlassPieces { get; set; } = new List<GlassPiece>();

    public virtual GlassConfiguration glassConfiguration { get; set; }

    public virtual GlassForProject glassProject { get; set; }

    public virtual OrnamentGlass hasOrnamentGlassNavigation { get; set; }

    public virtual OrnamentSpacer hasOrnamentSpacerNavigation { get; set; }
}