// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Image
{
    public int id { get; set; }

    public string caption { get; set; }

    public string imageType { get; set; }

    public byte[] imageData { get; set; }
}