// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Image
{
    public int id { get; set; }

    public int issue_id { get; set; }

    public string name { get; set; }

    public string imagePath { get; set; }

    public string imageType { get; set; }

    public DateTime? uploadDate { get; set; }

    public byte[] imageData { get; set; }

    public virtual Issue issue { get; set; }
}