// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Issue
{
    public int id { get; set; }

    public int project_id { get; set; }

    public string projectType { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public DateTime dateOfSubmission { get; set; }

    public DateTime? dateOfClosing { get; set; }

    public DateTime dueDate { get; set; }

    public string status { get; set; }

    public string priority { get; set; }

    public virtual ICollection<IssueImage> IssueImages { get; set; } = new List<IssueImage>();

    public virtual Project project { get; set; }
}