// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Leave
{
    public int id { get; set; }

    public int employee_id { get; set; }

    public DateTime startDate { get; set; }

    public DateTime? endDate { get; set; }

    public string reasonForLeave { get; set; }
}