// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Note
{
    public int id { get; set; }

    public int project_id { get; set; }

    public string projectType { get; set; }

    public string name { get; set; }

    public string text { get; set; }

    public virtual Project project { get; set; }
}