// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Notification
{
    public int id { get; set; }

    public int? project_id { get; set; }

    public string projectType { get; set; }

    public string title { get; set; }

    public string message { get; set; }

    public string priority { get; set; }

    public DateTime date { get; set; }

    public DateTime? dueDate { get; set; }

    public string status { get; set; }

    public virtual Project project { get; set; }
}