// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Order
{
    public int id { get; set; }

    public int subproject_id { get; set; }

    public int? otherSupplier_id { get; set; }

    public int? profileSupplier_id { get; set; }

    public int user_id { get; set; }

    public string name { get; set; }

    public string projectType { get; set; }

    public string description { get; set; }

    public DateTime dateOfOrder { get; set; }

    public DateTime? expectedDateOfOrder { get; set; }

    public int status { get; set; }

    public virtual OtherSupplier otherSupplier { get; set; }

    public virtual ProfileSupplier profileSupplier { get; set; }

    public virtual Subproject subproject { get; set; }

    public virtual User user { get; set; }
}