// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class ProfileSupplier
{
    public int id { get; set; }

    public string name { get; set; }

    public int oib { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public string adress { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public int? zipCode { get; set; }

    public string suppliesType { get; set; }

    public virtual ICollection<ALUProject> ALUProjects { get; set; } = new List<ALUProject>();

    public virtual ICollection<DoorProject> DoorProjects { get; set; } = new List<DoorProject>();

    public virtual ICollection<FacadeProject> FacadeProjects { get; set; } = new List<FacadeProject>();

    public virtual ICollection<PVCProject> PVCProjects { get; set; } = new List<PVCProject>();
}