// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class ProfileSupplier
{
    public int id { get; set; }

    public string name { get; set; }

    public int? oib { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public string adress { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public int? zipCode { get; set; }

    public string suppliesType { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}