// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Spacer
{
    public string name { get; set; }

    public string listOfPossibleThickness { get; set; }

    public int id { get; set; }
}