// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Step
{
    public int id { get; set; }

    public int task_id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string status { get; set; }

    public virtual Task task { get; set; }
}