// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Subproject
{
    public int id { get; set; }

    public int project_id { get; set; }

    public int projectType { get; set; }

    public string name { get; set; }

    public string profile { get; set; }

    public string colorOfFrame { get; set; }

    public string colorOfWing { get; set; }

    public string status { get; set; }

    public virtual ICollection<GlassForSubproject> GlassForSubprojects { get; set; } = new List<GlassForSubproject>();

    public virtual ICollection<Issue> Issues { get; set; } = new List<Issue>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual Project project { get; set; }
}