// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Task
{
    public int id { get; set; }

    public int subproject_id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public DateTime dateOfSubmission { get; set; }

    public DateTime? dateOfClosing { get; set; }

    public DateTime dueDate { get; set; }

    public int status { get; set; }

    public int priority { get; set; }

    public virtual ICollection<Step> Steps { get; set; } = new List<Step>();

    public virtual Subproject subproject { get; set; }
}