// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class ToolAssignmentCsite
{
    public int id { get; set; }

    public int employeeAssignedTo_id { get; set; }

    public int constructionSite_id { get; set; }

    public int tool_id { get; set; }

    public DateTime assignmentStartDate { get; set; }

    public DateTime? assignmentEndDate { get; set; }

    public virtual ConstructionSite constructionSite { get; set; }

    public virtual Employee employeeAssignedTo { get; set; }

    public virtual Tool tool { get; set; }
}