// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Tool
{
    public int id { get; set; }

    public string name { get; set; }

    public string serial_number { get; set; }

    public string type { get; set; }

    public string manufacturer { get; set; }

    public DateTime warrantyExpiry { get; set; }

    public string notes { get; set; }

    public virtual ICollection<ToolAssignmentCsite> ToolAssignmentCsites { get; set; } = new List<ToolAssignmentCsite>();
}