// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class User
{
    public int user_id { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public int role { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}