// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Vehicle
{
    public int id { get; set; }

    public string name { get; set; }

    public string model { get; set; }

    public string licensePlate { get; set; }

    public DateTime registrationValidTo { get; set; }

    public string manufacturer { get; set; }

    public string fuelType { get; set; }

    public int? noOfSeats { get; set; }

    public int productionYear { get; set; }

    public int isCurrentlyAssigned { get; set; }

    public virtual ICollection<VehicleAssignmentCSite> VehicleAssignmentCSites { get; set; } = new List<VehicleAssignmentCSite>();
}