// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Bussiness_Logic_Layer
{
    public partial class EstimateProductionTime
    {
        /// <summary>
        /// model input class for EstimateProductionTime.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"OrderID")]
            public float OrderID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ProductType")]
            public string ProductType { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Material")]
            public string Material { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Width_mm")]
            public float Width_mm { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Height_mm")]
            public float Height_mm { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"GlassType")]
            public string GlassType { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Color")]
            public string Color { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"OperatorExperienceYears")]
            public float OperatorExperienceYears { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"EstimatedProductionTime_min")]
            public float EstimatedProductionTime_min { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"ActualProductionTime_min")]
            public float ActualProductionTime_min { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"ProductionCost_EUR")]
            public float ProductionCost_EUR { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"DeliveryTime_days")]
            public float DeliveryTime_days { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Area_m2")]
            public float Area_m2 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"AspectRatio")]
            public float AspectRatio { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"TotalArea_m2")]
            public float TotalArea_m2 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for EstimateProductionTime.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"OrderID")]
            public float OrderID { get; set; }

            [ColumnName(@"ProductType")]
            public float[] ProductType { get; set; }

            [ColumnName(@"Material")]
            public float[] Material { get; set; }

            [ColumnName(@"Width_mm")]
            public float Width_mm { get; set; }

            [ColumnName(@"Height_mm")]
            public float Height_mm { get; set; }

            [ColumnName(@"GlassType")]
            public float[] GlassType { get; set; }

            [ColumnName(@"Color")]
            public float[] Color { get; set; }

            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"OperatorExperienceYears")]
            public float OperatorExperienceYears { get; set; }

            [ColumnName(@"EstimatedProductionTime_min")]
            public float EstimatedProductionTime_min { get; set; }

            [ColumnName(@"ActualProductionTime_min")]
            public float ActualProductionTime_min { get; set; }

            [ColumnName(@"ProductionCost_EUR")]
            public float ProductionCost_EUR { get; set; }

            [ColumnName(@"DeliveryTime_days")]
            public float DeliveryTime_days { get; set; }

            [ColumnName(@"Area_m2")]
            public float Area_m2 { get; set; }

            [ColumnName(@"AspectRatio")]
            public float AspectRatio { get; set; }

            [ColumnName(@"TotalArea_m2")]
            public float TotalArea_m2 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.Combine(AppContext.BaseDirectory, "Models\\EstimateDeliveryDays.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
