// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Transforms;

namespace Bussiness_Logic_Layer
{
    public partial class EstimateProductionTime
    {
        public const string RetrainFilePath =  @"C:\Users\user\Downloads\windows_doors_dataset_enhanced_2000.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"ProductType", @"ProductType"),new InputOutputColumnPair(@"Material", @"Material"),new InputOutputColumnPair(@"GlassType", @"GlassType"),new InputOutputColumnPair(@"Color", @"Color")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"OrderID", @"OrderID"),new InputOutputColumnPair(@"Width_mm", @"Width_mm"),new InputOutputColumnPair(@"Height_mm", @"Height_mm"),new InputOutputColumnPair(@"Quantity", @"Quantity"),new InputOutputColumnPair(@"OperatorExperienceYears", @"OperatorExperienceYears"),new InputOutputColumnPair(@"EstimatedProductionTime_min", @"EstimatedProductionTime_min"),new InputOutputColumnPair(@"ProductionCost_EUR", @"ProductionCost_EUR"),new InputOutputColumnPair(@"DeliveryTime_days", @"DeliveryTime_days"),new InputOutputColumnPair(@"Area_m2", @"Area_m2"),new InputOutputColumnPair(@"AspectRatio", @"AspectRatio"),new InputOutputColumnPair(@"TotalArea_m2", @"TotalArea_m2")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"ProductType",@"Material",@"GlassType",@"Color",@"OrderID",@"Width_mm",@"Height_mm",@"Quantity",@"OperatorExperienceYears",@"EstimatedProductionTime_min",@"ProductionCost_EUR",@"DeliveryTime_days",@"Area_m2",@"AspectRatio",@"TotalArea_m2"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=1505,NumberOfLeaves=3931,FeatureFraction=1F,LabelColumnName=@"ActualProductionTime_min",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
 }
